apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      serviceAccountName: petclinic-sa
      containers:
        - name: petclinic
          image: petclinicacrpy2t5evhiqdr4.azurecr.io/spring-petclinic:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "postgres"
            - name: POSTGRES_URL
              value: "jdbc:postgresql://postgres-petclinic-py2t5evhiqdr4.postgres.database.azure.com:5432/petclinic?sslmode=require"
            - name: AZURE_MANAGED_IDENTITY_NAME
              value: "petclinic-app-uami-yqkjlqj5mgv34"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
