apiVersion: v1
kind: Secret
metadata:
  name: acr-pull-secret
  namespace: petclinic
  annotations:
    kubernetes.io/dockerconfigjson: ".dockerconfigjson"
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "<your_acr_login_server>": {
          "username": "<acr-username>",
          "password": "<acr-password>",
          "email": "<you@example.com>"
        }
      }
    }
type: kubernetes.io/dockerconfigjson
